"""Replay scenario suite -> evidence/runs/* + evidence/SCENARIOS.md index.

Each scenario is exactly what a caller would run (`python -m cua replay ...`). The
fault injection (`--chaos`) is a test-harness hook on the mock app; the replay engine
does not know it is being tested.

    python scripts/run_scenarios.py            # all scenarios
    python scripts/run_scenarios.py notice     # only scenarios whose name contains 'notice'
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BAL = "member.get_savings_balance"
SHARE = "share.open_account_to_review"

SCENARIOS: list[dict] = [
    {"name": "happy-path", "why": "Replay with the discovery input", "args": [BAL, "--input", "member_id=100234"]},
    {"name": "happy-path-other-member", "why": "Same artifact, different input (parameterisation)", "args": [BAL, "--input", "member_id=100871"]},
    {"name": "business-not-found", "why": "Legitimate business result, not a crash", "args": [BAL, "--input", "member_id=99999"]},
    {"name": "business-permission-denied", "why": "Operator not entitled to the record", "args": [BAL, "--input", "member_id=55555"]},
    {"name": "business-host-validation", "why": "Passes our schema, rejected by the host", "args": [BAL, "--input", "member_id=123456789"]},
    {"name": "rejected-bad-input", "why": "Pre-flight validation; UI never touched", "args": [BAL, "--input", "member_id=12ab"]},
    {"name": "recovered-system-notice", "why": "Known interstitial dismissed", "args": [BAL, "--input", "member_id=100234", "--chaos", '{"notice": true}']},
    {"name": "recovered-session-expired", "why": "Session timeout -> re-auth -> restart (no irreversible step yet)", "args": [BAL, "--input", "member_id=100234", "--chaos", '{"expire_after": 3}']},
    {"name": "recovered-host-busy", "why": "Transient 503 -> reload", "args": [BAL, "--input", "member_id=100234", "--chaos", '{"transient_path": "/work/member/"}']},
    {"name": "failed-app-error", "why": "Unhandled host error -> hard failure with evidence bundle", "args": [BAL, "--input", "member_id=100234", "--chaos", '{"error_path": "/work/member/"}']},
    {"name": "failed-human-required", "why": "Supervisor override needed, escalation disabled", "args": [BAL, "--input", "member_id=77777"]},
    {"name": "escalated-supervisor-override", "why": "Live-session handoff to an operator, then resume", "args": [BAL, "--input", "member_id=77777", "--escalate", "--operator-bot", "--escalation-timeout", "90"]},
    {"name": "tenant-bayside-base-artifact", "why": "Same vendor product, relabelled UI: drift detected and pinpointed", "args": [BAL, "--tenant", "bayside", "--input", "member_id=100234", "--no-overlays"]},
    {"name": "tenant-bayside-with-overlay", "why": "Shared artifact + minimal tenant overlay", "args": [BAL, "--tenant", "bayside", "--input", "member_id=100234"]},
    {"name": "share-review-happy-path", "why": "Second capability: multi-field form to the review screen (never confirms)", "args": [SHARE, "--input", "member_id=100871", "--input", "share_type=VACATION CLUB", "--input", "initial_deposit=50.00"]},
    {"name": "rejected-irreversible-unconfirmed", "why": "Capability with an irreversible Confirm step, no caller confirmation -> refused before touching the UI", "args": ["evidence/policy/share.open_account_and_confirm.json", "--allow-draft", "--input", "member_id=100871", "--input", "share_type=VACATION CLUB", "--input", "initial_deposit=50.00"]},
    {"name": "share-review-validation", "why": "Host rejects the deposit amount -> business outcome", "args": [SHARE, "--input", "member_id=100871", "--input", "share_type=VACATION CLUB", "--input", "initial_deposit=50.5"]},
]


def main() -> None:
    only = sys.argv[1] if len(sys.argv) > 1 else ""
    rows = []
    for sc in SCENARIOS:
        if only and only not in sc["name"]:
            continue
        cmd = [sys.executable, "-m", "cua", "replay", *sc["args"]]
        p = subprocess.run(cmd, cwd=ROOT, capture_output=True, text=True)
        try:
            out = json.loads(p.stdout[p.stdout.index("{\n  \"schema\""):])
        except ValueError:
            print(p.stdout, p.stderr)
            raise
        run_dir = Path(out["evidence_dir"]).name
        detail = (out.get("outcome") or {}).get("code") or (out.get("error") or {}).get("code") or ""
        rec = ", ".join(r["code"] for r in out.get("recoveries", []))
        iv = ", ".join(f"{i['id']} by {i.get('operator')}" for i in out.get("interventions", []))
        warn = len(out.get("warnings", []))
        rows.append((sc["name"], sc["why"], out["status"], detail, rec, iv, warn, run_dir, " ".join(["python -m cua replay", *[
            f"'{a}'" if (" " in a or "{" in a) else a for a in sc["args"]]])))
        print(f"{sc['name']:32s} {out['status']:17s} {detail:28s} {rec}")
    if only:
        return
    lines = ["# Replay scenarios", "", "Generated by `python scripts/run_scenarios.py`. Each run directory under `runs/` holds",
             "`events.jsonl` (structured, redacted log), `result.json` (redacted result), `screens/` (masked screenshots)",
             "and, on failure, `failure/` (redacted DOM per frame + the observation the engine saw).", "",
             "| scenario | why | status | outcome / error | recoveries | interventions | warnings | run |", "|---|---|---|---|---|---|---|---|"]
    for n, why, st, det, rec, iv, w, rd, _ in rows:
        lines.append(f"| {n} | {why} | `{st}` | {f'`{det}`' if det else ''} | {rec} | {iv} | {w or ''} | [`{rd}`](runs/{rd}/) |")
    lines += ["", "## Commands", ""]
    for n, *_, cmd in rows:
        lines.append(f"- **{n}**: `{cmd}`")
    (ROOT / "evidence" / "SCENARIOS.md").write_text("\n".join(lines) + "\n")
    print("wrote evidence/SCENARIOS.md")


if __name__ == "__main__":
    main()
